# Generated by Django 5.0.3 on 2024-03-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='dataemprestimo',
            field=models.DateField(),
        ),
    ]
