# Generated by Django 5.0.3 on 2024-03-11 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_emprestimo_dataemprestimo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='usuarios',
            new_name='usuario',
        ),
    ]
