# Generated by Django 5.0.3 on 2024-03-18 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_usuarios_emprestimo_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livro',
            options={'verbose_name_plural': 'livro'},
        ),
    ]
